import { authOptions } from "@/app/api/auth/[...nextauth]/next-auth-options";
import Header from "@/app/header";
import Menu from "@/app/menu";
import { NextAuthProvider } from "@/app/provider/next-auth";
import {
  AppShell,
  AppShellHeader,
  AppShellMain,
  AppShellNavbar,
  ColorSchemeScript,
  MantineProvider,
} from "@mantine/core";
import "@mantine/core/styles.css";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { Inter } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="jp">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={inter.className}>
        <NextTopLoader showSpinner={false} />
        <NextAuthProvider>
          <MantineProvider>
            <AppShell
              header={{ height: 60 }}
              navbar={{
                width: session != null ? 250 : 0,
                breakpoint: "xs",
                collapsed: { mobile: true, desktop: false },
              }}
            >
              <AppShellHeader>
                <Header />
              </AppShellHeader>

              {session && (
                <AppShellNavbar>
                  <Menu />
                </AppShellNavbar>
              )}

              <AppShellMain>{children}</AppShellMain>
            </AppShell>
          </MantineProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
